apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xsnizla2c-nodejs
  janus-idp.io/tekton: xsnizla2c-nodejs
  backstage.io/kubernetes-id: xsnizla2c-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xsnizla2c-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
